//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Martijn van Adrichem, Duncan Verbrugge")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Wrapper around RabbitMQ")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.4.2.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.4.2")]
[assembly: System.Reflection.AssemblyProductAttribute("Minor.Nijn.WebScale")]
[assembly: System.Reflection.AssemblyTitleAttribute("Minor.Nijn.WebScale")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.4.2.0")]

// Generated by the MSBuild WriteCodeFragment class.

